databaseChangeLog:
  - changeSet:
    id: sentensiado_estado_fk
    author: alejandro.hernandez
    changes:
      - addForeignKeyConstraint:
          baseColumnNames: estado_id
          baseTableName: sentensiado
          constraintName: fk_sentensiado_estado
          deferrable: false
          initiallyDeferred: false
          referencedColumnNames: id
          referencedTableName: estado
  - changeSet:
    id: sentensiado_pais_fk
    author: alejandro.hernandez
    changes:
      - addForeignKeyConstraint:
          baseColumnNames: pais_id
          baseTableName: sentensiado
          constraintName: fk_sentensiado_pais
          deferrable: false
          initiallyDeferred: false
          referencedColumnNames: id
          referencedTableName: pais